using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using BusineesLogic.domain;

public partial class site1_Employee : System.Web.UI.Page
{
    private EmployeeDAO employee = new EmployeeDAO();
    private UserDTO userDtoUpdate;
    private UserDTO userDto;
    private HolidaysDTO empHolidays;
    protected void Page_Load(object sender, EventArgs e)
    {
        loadSession();
        accessRights();
        if (!IsPostBack)
            loadEmployees();
    }
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
    protected void GridView1_SelectedIndexChanged1(object sender, EventArgs e)
    {

    }
    protected void Register_Click(object sender, EventArgs e)
    {
        Response.Redirect("AddEmployee.aspx");
    }
    protected void Submit_Click(object sender, EventArgs e)
    {
        Session.Abandon();
        Session.Clear();
        Response.Redirect("Default.aspx");
    }

    private void loadEmployees()
    {
        try
        {
            GridView1.DataSource = employee.populateGrid();
            GridView1.DataBind();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }

    private void loadSession()
    {

        userDtoUpdate = (UserDTO)Session["userUpdate"];
        Session.Remove("userUpdate");
        userDto = (UserDTO)Session["userDto"];
        if (userDto == null)
            Response.Redirect("Default.aspx");
        userDtoUpdate = (UserDTO)Session["userUpdate"];
        Session.Remove("userUpdate");
        lblUser.Text = userDto.username;

        if (userDto.userTypeName.Trim() != "Admin")
        {
            AdminLinkPanel.Visible = false;
            Response.Redirect("Home.aspx");
        }
        else
            userPanel.Visible = false;
    }

    private void accessRights()
    {
        GridView1.AutoGenerateSelectButton = true;
        //rights code 
        if (userDto.userTypeName.Trim() != "Admin")
        {
            GridView1.AutoGenerateDeleteButton = false;
            GridView1.AutoGenerateEditButton = false;
        }
        else
        {
            GridView1.AutoGenerateDeleteButton = true;
            GridView1.AutoGenerateEditButton = true;
        }
    }

    private void ExceptionRedirect(Exception ex)
    {
        Response.Redirect("ErrorPage.aspx?ErrorMessage=" + ex.Message.Replace('\n', ' '), false);
    }
    protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        try
        {
            string id = GridView1.Rows[e.RowIndex].Cells[1].Text;
            employee.delete(id);
            loadEmployees();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }
    protected void GridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
    {
        GridView1.EditIndex = -1;
        loadEmployees();
    }
    protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
    {
        GridView1.EditIndex = e.NewEditIndex;
        loadEmployees();
    }
    protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
    {
        List<string> employeeDetails = new List<string>();
        GridViewRow row = GridView1.Rows[e.RowIndex];
        string id = GridView1.Rows[e.RowIndex].Cells[1].Text;
        try
        {
            employeeDetails.Add(((TextBox)row.Cells[2].Controls[0]).Text); //name
            employeeDetails.Add(((TextBox)row.Cells[3].Controls[0]).Text); //surname
            employeeDetails.Add(((TextBox)row.Cells[4].Controls[0]).Text); //cell number
            employeeDetails.Add(((TextBox)row.Cells[5].Controls[0]).Text); //streetname
            employeeDetails.Add(((TextBox)row.Cells[6].Controls[0]).Text); //suburb
            employeeDetails.Add(((TextBox)row.Cells[7].Controls[0]).Text); //postalCode
            employee.update(id, employeeDetails);
            GridView1.EditIndex = -1;
            loadEmployees();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }
    protected void GridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
    {
        GridView1.PageIndex = e.NewPageIndex;
        loadEmployees();
    }

    protected void btnHolidays_Click(object sender, EventArgs e)
    {
        lblAppproved.Visible = false;
        bool leaveDays = testForNumber(txtLeaveDays.Text);
        bool religiousDays = testForNumber(txtReligiousDays.Text);
        bool sickDays = testForNumber(txtSickDays.Text);

        if (lblID.Text != "No Employee Selected")
        {
            GridViewRow row = GridView1.SelectedRow;
            string id = row.Cells[1].Text;
            if (leaveDays == true && religiousDays == true && sickDays == true)
            {
                empHolidays = new HolidaysDTO.HolidaysBuilder()
            .buildEmpID(userDto.Id)
            .buidlDaysExcPublic(Convert.ToInt32(txtLeaveDays.Text))
            .buildReligiousDays(Convert.ToInt32(txtReligiousDays.Text))
            .buildSickLeave(Convert.ToInt32(txtSickDays.Text))
            .build();
                employee.saveHoliday(empHolidays,id);
                lblAppproved.Visible = true;
                txtLeaveDays.Text = String.Empty;
                txtReligiousDays.Text = String.Empty;
                txtSickDays.Text = String.Empty;
            }
        }
    }
    protected void btnSetDays_Click(object sender, EventArgs e)
    {
        if (GridView1.SelectedIndex >= 0)
        {
            GridViewRow row = GridView1.SelectedRow;
            lblID.Text = row.Cells[2].Text + " " + row.Cells[3].Text;
        }
    }
    private bool testForNumber(string number)
    {
        int temp;
        return int.TryParse(number, out temp);
    }
}