using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class site1_Suppliers : System.Web.UI.Page
{
    private UserDTO userDto;
    private UserDTO userDtoUpdate;
    private SupplierDAO supplier = new SupplierDAO();
    protected void Page_Load(object sender, EventArgs e)
    {
        loadSession();
        accessRights();
        if (!IsPostBack)
            loadSuppliers();
    }
    protected void Register_Click(object sender, EventArgs e)
    {
        Response.Redirect("AddSupplier.aspx");
    }
    protected void Submit_Click(object sender, EventArgs e)
    {
        Session.Abandon();
        Session.Clear();
        Response.Redirect("Default.aspx");
    }
    private void loadSession()
    {
        userDtoUpdate = (UserDTO)Session["userUpdate"];
        Session.Remove("userUpdate");
        userDto = (UserDTO)Session["userDto"];
        if (userDto == null)
            Response.Redirect("Default.aspx");
        lblUser.Text = userDto.username;

        if (userDto.userTypeName.Trim() != "Admin")
            AdminLinkPanel.Visible = false;
        else
            userPanel.Visible = false;
    }

    private void loadSuppliers()
    {
        try
        {
            GridView1.DataSource = supplier.populateGrid();
            GridView1.DataBind();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }

    private void accessRights()
    {
        GridView1.AutoGenerateSelectButton = true;
        //rights code 
        if (userDto.userTypeName.Trim() != "Admin")
        {
            GridView1.AutoGenerateDeleteButton = false;
            GridView1.AutoGenerateEditButton = false;
        }
        else
        {
            GridView1.AutoGenerateDeleteButton = true;
            GridView1.AutoGenerateEditButton = true;
        }
    }

    protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        try
        {
            string id = GridView1.Rows[e.RowIndex].Cells[1].Text;
            supplier.delete(id);
            loadSuppliers();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }

    private void ExceptionRedirect(Exception ex)
    {
        Response.Redirect("ErrorPage.aspx?ErrorMessage=" + ex.Message.Replace('\n', ' '), false);
    }
    protected void GridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
    {
        GridView1.EditIndex = -1;
        loadSuppliers();
    }
    protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
    {

        GridView1.EditIndex = e.NewEditIndex;
        loadSuppliers();


    }
    protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
    {
        List<string> supplierDetails = new List<string>();
        GridViewRow row = GridView1.Rows[e.RowIndex];
        string id = GridView1.Rows[e.RowIndex].Cells[1].Text;
        try
        {
            supplierDetails.Add(((TextBox)row.Cells[2].Controls[0]).Text); //name
            supplierDetails.Add(((TextBox)row.Cells[3].Controls[0]).Text); //surname
            supplierDetails.Add(((TextBox)row.Cells[4].Controls[0]).Text); //cellnumber 
            supplierDetails.Add(((TextBox)row.Cells[5].Controls[0]).Text); //streetName
            supplierDetails.Add(((TextBox)row.Cells[6].Controls[0]).Text); //suburb
            supplierDetails.Add(((TextBox)row.Cells[7].Controls[0]).Text); //postal code

            supplier.update(id, supplierDetails);
            GridView1.EditIndex = -1;
            loadSuppliers();
        }
        catch (Exception ex)
        {
            ExceptionRedirect(ex);
        }
    }
    protected void GridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
    {
        GridView1.PageIndex = e.NewPageIndex;
        loadSuppliers();
    }
    protected void dgrvData_Filter(object sender, EventArgs e)
    {
        if (testForNumber(txtSearch.Text) != false || txtSearch.Text == String.Empty)
        {
            DataTable searchedOrder = new DataTable();


            if (txtSearch.Text.ToString().Trim().Length == 0)
                loadSuppliers();
            else
            {
                try
                {
                    GridView1.DataSource = supplier.searchSupplier(txtSearch.Text);
                    GridView1.DataBind();
                }
                catch (Exception ex)
                {
                    ExceptionRedirect(ex);
                }
            }
        }
    }
    protected void btnSearch_Click(object sender, EventArgs e)
    {
        
    }

    private bool testForNumber(string number)
    {
        int temp;
        return int.TryParse(number, out temp);
    }
}